name: Clang Format

on:
  push:
    paths:
      - ".github/workflows/clang-format-lint.yml"
      - "app/boards/**/*.c"
      - "app/include/**/*.h"
      - "app/src/**"
      - "app/drivers/**/*.c"
      - "app/drivers/**/*.h"
  pull_request:
    paths:
      - ".github/workflows/clang-format-lint.yml"
      - "app/boards/**/*.c"
      - "app/include/**/*.h"
      - "app/src/**"
      - "app/drivers/**/*.c"
      - "app/drivers/**/*.h"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.11
        with:
          source: "./app"
          extensions: "h,c"
