name: Docs Checks

on:
  push:
    paths:
      - ".github/workflows/doc-checks.yml"
      - "docs/**"
  pull_request:
    paths:
      - ".github/workflows/doc-checks.yml"
      - "docs/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: docs
      - name: ESLint
        run: npm run lint
        working-directory: docs
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          working-directory: docs
      - name: Prettier check
        run: npm run prettier:check
        working-directory: docs
